import type { PrismaClient } from "@prisma/client";
import type { Migration } from "../runner";

// ---------------------------------------------------------------------------
// Migration 001: Baseline — Create all 32 model tables + indexes
// ---------------------------------------------------------------------------
// IMMUTABILITY INVARIANT:
// This file contains a frozen, static SQL definition of the baseline database
// schema. It does NOT import or depend on any generated DDL artifacts at runtime.
//
// Future schema changes MUST be introduced as new numbered migration files
// (e.g. 005_..., 006_...) and MUST NEVER alter this baseline snapshot.
// ---------------------------------------------------------------------------

const BASELINE_TABLES: string[] = [
  `CREATE TABLE IF NOT EXISTS vehicles (
  id TEXT PRIMARY KEY NOT NULL,
  vehicle_number TEXT NOT NULL UNIQUE,
  party_id TEXT,
  party_name TEXT,
  company_body_qty REAL,
  extra_body_qty REAL,
  vehicle_type TEXT,
  trip_count INTEGER NOT NULL DEFAULT 0,
  engine_hours REAL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)`,
  `CREATE TABLE IF NOT EXISTS parties (
  id TEXT PRIMARY KEY NOT NULL,
  party_name TEXT NOT NULL UNIQUE,
  phone TEXT,
  address TEXT,
  party_group TEXT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)`,
  `CREATE TABLE IF NOT EXISTS materials (
  id TEXT PRIMARY KEY NOT NULL,
  material_name TEXT NOT NULL UNIQUE,
  rate_per_cft REAL NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)`,
  `CREATE TABLE IF NOT EXISTS outgoing_sales (
  id TEXT PRIMARY KEY NOT NULL,
  sale_date DATETIME NOT NULL,
  serial_number INTEGER UNIQUE,
  book_number INTEGER,
  page_number INTEGER,
  vehicle_id TEXT,
  party_id TEXT,
  material_id TEXT,
  vehicle_number TEXT NOT NULL,
  party_name TEXT NOT NULL,
  material_name TEXT NOT NULL,
  rate_per_cft REAL NOT NULL,
  qty REAL NOT NULL,
  original_qty REAL,
  quantity_reason TEXT,
  trip_delta INTEGER NOT NULL DEFAULT 1,
  discount_type TEXT NOT NULL DEFAULT 'fixed',
  discount_value REAL NOT NULL DEFAULT 0,
  amount REAL NOT NULL,
  gst_enabled BOOLEAN NOT NULL DEFAULT 0,
  gst_rate REAL NOT NULL DEFAULT 5,
  sgst REAL NOT NULL DEFAULT 0,
  cgst REAL NOT NULL DEFAULT 0,
  gst_amount REAL NOT NULL DEFAULT 0,
  final_amount REAL NOT NULL,
  cash_paid REAL NOT NULL DEFAULT 0,
  bank_paid REAL NOT NULL DEFAULT 0,
  gpay_paid REAL NOT NULL DEFAULT 0,
  paid_total REAL NOT NULL DEFAULT 0,
  remaining_credit REAL NOT NULL DEFAULT 0,
  remarks TEXT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)`,
  `CREATE TABLE IF NOT EXISTS financial_events (
  id TEXT PRIMARY KEY NOT NULL,
  event_id TEXT NOT NULL UNIQUE,
  correlation_id TEXT NOT NULL,
  event_type TEXT NOT NULL,
  entity_type TEXT NOT NULL,
  entity_id TEXT NOT NULL,
  schema_version INTEGER NOT NULL DEFAULT 1,
  payload JSON NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)`,
  `CREATE TABLE IF NOT EXISTS ledger_entries (
  id TEXT PRIMARY KEY NOT NULL,
  financial_event_id TEXT NOT NULL UNIQUE,
  correlation_id TEXT NOT NULL,
  event_type TEXT NOT NULL,
  entity_type TEXT NOT NULL,
  entity_id TEXT NOT NULL,
  entry_date DATETIME NOT NULL,
  cash_amount REAL NOT NULL DEFAULT 0,
  bank_amount REAL NOT NULL DEFAULT 0,
  gpay_amount REAL NOT NULL DEFAULT 0,
  credit_amount REAL NOT NULL DEFAULT 0,
  total_amount REAL NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)`,
  `CREATE TABLE IF NOT EXISTS day_books (
  id TEXT PRIMARY KEY NOT NULL,
  business_date DATETIME NOT NULL UNIQUE,
  opening_cash_balance REAL NOT NULL DEFAULT 0,
  opening_bank_balance REAL NOT NULL DEFAULT 0,
  cash_sales_total REAL NOT NULL DEFAULT 0,
  bank_sales_total REAL NOT NULL DEFAULT 0,
  gpay_sales_total REAL NOT NULL DEFAULT 0,
  expense_total REAL NOT NULL DEFAULT 0,
  closing_cash_balance REAL NOT NULL DEFAULT 0,
  closing_bank_balance REAL NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)`,
  `CREATE TABLE IF NOT EXISTS day_book_expense_entries (
  id TEXT PRIMARY KEY NOT NULL,
  day_book_id TEXT NOT NULL,
  source_event_id TEXT NOT NULL UNIQUE,
  expense_type TEXT NOT NULL,
  entry_date DATETIME NOT NULL,
  amount REAL NOT NULL,
  description TEXT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (day_book_id) REFERENCES day_books(id) ON DELETE CASCADE
)`,
  `CREATE TABLE IF NOT EXISTS incoming_boulder (
  id TEXT PRIMARY KEY NOT NULL,
  date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  book_number INTEGER,
  page_number INTEGER,
  vehicle_id TEXT,
  party_id TEXT,
  material_id TEXT,
  vehicle_number TEXT NOT NULL,
  party_name TEXT NOT NULL,
  material_name TEXT NOT NULL DEFAULT 'ROCK',
  qty REAL NOT NULL,
  remarks TEXT,
  time TEXT,
  rock_rate REAL NOT NULL DEFAULT 26,
  amount REAL NOT NULL DEFAULT 0,
  cash_paid REAL NOT NULL DEFAULT 0,
  bank_paid REAL NOT NULL DEFAULT 0,
  gpay_paid REAL NOT NULL DEFAULT 0,
  paid_total REAL NOT NULL DEFAULT 0,
  remaining_credit REAL NOT NULL DEFAULT 0,
  settled BOOLEAN NOT NULL DEFAULT 0,
  vehicle_rent REAL NOT NULL DEFAULT 0,
  combined_payment BOOLEAN NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)`,
  `CREATE TABLE IF NOT EXISTS party_credit (
  id TEXT PRIMARY KEY NOT NULL,
  party_id TEXT,
  party_name TEXT NOT NULL,
  sale_id TEXT NOT NULL,
  amount REAL NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',\n  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (sale_id) REFERENCES outgoing_sales(id) ON DELETE CASCADE
)`,
  `CREATE TABLE IF NOT EXISTS party_collections (
  id TEXT PRIMARY KEY NOT NULL,
  party_id TEXT,
  party_name TEXT NOT NULL,
  collection_date DATETIME NOT NULL,
  cash_paid REAL NOT NULL DEFAULT 0,
  bank_paid REAL NOT NULL DEFAULT 0,
  gpay_paid REAL NOT NULL DEFAULT 0,
  total_amount REAL NOT NULL,
  remarks TEXT,
  source_event_id TEXT NOT NULL UNIQUE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)`,
  `CREATE TABLE IF NOT EXISTS party_ledger (
  id TEXT PRIMARY KEY NOT NULL,
  party_id TEXT,
  party_name TEXT NOT NULL,
  date DATETIME NOT NULL,
  time TEXT,
  type TEXT NOT NULL,
  ref_id TEXT NOT NULL,
  description TEXT NOT NULL,
  payment_method TEXT,
  debit_amount REAL NOT NULL DEFAULT 0,
  credit_amount REAL NOT NULL DEFAULT 0,
  balance REAL NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)`,
  `CREATE TABLE IF NOT EXISTS cash_transfers (
  id TEXT PRIMARY KEY NOT NULL,
  date DATETIME NOT NULL,
  time TEXT NOT NULL,
  type TEXT NOT NULL,
  amount REAL NOT NULL,
  user_name TEXT NOT NULL,
  remarks TEXT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)`,
  `CREATE TABLE IF NOT EXISTS party_payments (
  id TEXT PRIMARY KEY NOT NULL,
  party_id TEXT,
  party_name TEXT NOT NULL,
  payment_date DATETIME NOT NULL,
  cash_paid REAL NOT NULL DEFAULT 0,
  bank_paid REAL NOT NULL DEFAULT 0,
  gpay_paid REAL NOT NULL DEFAULT 0,
  total_amount REAL NOT NULL,
  remarks TEXT,
  source_event_id TEXT NOT NULL UNIQUE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)`,
  `CREATE TABLE IF NOT EXISTS employee_credit (
  id TEXT PRIMARY KEY NOT NULL,
  employee_name TEXT NOT NULL,
  amount REAL NOT NULL,
  reason TEXT,
  expected_due_date DATETIME,
  status TEXT NOT NULL DEFAULT 'pending',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)`,
  `CREATE TABLE IF NOT EXISTS suppliers (
  id TEXT PRIMARY KEY NOT NULL,
  supplier_name TEXT NOT NULL UNIQUE,
  phone TEXT,
  address TEXT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)`,
  `CREATE TABLE IF NOT EXISTS day_book_entries (
  id TEXT PRIMARY KEY NOT NULL,
  entry_date DATETIME NOT NULL,
  entry_type TEXT NOT NULL,
  reference TEXT,
  description TEXT,
  debit REAL NOT NULL DEFAULT 0,
  credit REAL NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)`,
  `CREATE TABLE IF NOT EXISTS audit_logs (
  id TEXT PRIMARY KEY NOT NULL,
  entity_name TEXT NOT NULL,
  entity_id TEXT NOT NULL,
  action TEXT NOT NULL,
  payload TEXT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)`,
  `CREATE TABLE IF NOT EXISTS roles (
  id TEXT PRIMARY KEY NOT NULL,
  role_name TEXT NOT NULL UNIQUE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)`,
  `CREATE TABLE IF NOT EXISTS other_credits (
  id TEXT PRIMARY KEY NOT NULL,
  name TEXT NOT NULL,
  amount REAL NOT NULL,
  reason TEXT,
  expected_due_date DATETIME,
  status TEXT NOT NULL DEFAULT 'pending',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)`,
  `CREATE TABLE IF NOT EXISTS expenses (
  id TEXT PRIMARY KEY NOT NULL,
  expense_date DATETIME NOT NULL,
  expense_type TEXT NOT NULL,
  amount REAL NOT NULL,
  payment_mode TEXT NOT NULL DEFAULT 'CASH',
  party_id TEXT,
  party_name TEXT,
  vehicle_id TEXT,
  vehicle_number TEXT,
  description TEXT,
  source_event_id TEXT NOT NULL UNIQUE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)`,
  `CREATE TABLE IF NOT EXISTS employees (
  id TEXT PRIMARY KEY NOT NULL,
  name TEXT NOT NULL UNIQUE,
  phone TEXT,
  address TEXT,
  role TEXT NOT NULL DEFAULT 'STAFF',
  balance REAL NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)`,
  `CREATE TABLE IF NOT EXISTS employee_ledgers (
  id TEXT PRIMARY KEY NOT NULL,
  employee_id TEXT NOT NULL,
  date DATETIME NOT NULL,
  type TEXT NOT NULL,
  amount REAL NOT NULL,
  balance REAL NOT NULL,
  description TEXT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE
)`,
  `CREATE TABLE IF NOT EXISTS fuel_purchases (
  id TEXT PRIMARY KEY NOT NULL,
  date DATETIME NOT NULL,
  fuel_type TEXT NOT NULL DEFAULT 'DIESEL',
  price_per_litre REAL,
  qty_litre REAL,
  amount REAL NOT NULL,
  paid_amount REAL NOT NULL DEFAULT 0,
  credit_amount REAL NOT NULL DEFAULT 0,
  is_can BOOLEAN NOT NULL DEFAULT 0,
  vehicle_id TEXT,
  vehicle_number TEXT,
  source_event_id TEXT NOT NULL UNIQUE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)`,
  `CREATE TABLE IF NOT EXISTS sync_state (
  id TEXT PRIMARY KEY NOT NULL DEFAULT 'default',
  last_synced_at DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00',
  status TEXT NOT NULL DEFAULT 'IDLE',
  last_error TEXT,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)`,
  `CREATE TABLE IF NOT EXISTS global_settings (
  id TEXT PRIMARY KEY NOT NULL DEFAULT 'default',
  quarry_name TEXT NOT NULL DEFAULT 'MBM Quarry',
  gst_number TEXT NOT NULL DEFAULT '',
  address TEXT NOT NULL DEFAULT '',
  phone TEXT NOT NULL DEFAULT '',
  default_printer TEXT NOT NULL DEFAULT '',
  backup_folder TEXT NOT NULL DEFAULT '',
  admin_pin TEXT NOT NULL DEFAULT '8888',
  delete_pin TEXT NOT NULL DEFAULT '7711',
  enable_weighbridge BOOLEAN NOT NULL DEFAULT 0,
  enable_fleet_maintenance BOOLEAN NOT NULL DEFAULT 0,
  enable_customer_portal BOOLEAN NOT NULL DEFAULT 0,
  enable_credit_locks BOOLEAN NOT NULL DEFAULT 0,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)`,
  `CREATE TABLE IF NOT EXISTS inventory_stock (
  id TEXT PRIMARY KEY NOT NULL,
  material_name TEXT NOT NULL UNIQUE,
  quantity REAL NOT NULL DEFAULT 0,
  unit TEXT NOT NULL DEFAULT 'TONS',
  last_updated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)`,
  `CREATE TABLE IF NOT EXISTS inventory_transactions (
  id TEXT PRIMARY KEY NOT NULL,
  stock_id TEXT NOT NULL,
  date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  type TEXT NOT NULL,
  quantity_change REAL NOT NULL,
  reference_id TEXT,
  description TEXT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (stock_id) REFERENCES inventory_stock(id) ON DELETE CASCADE
)`,
  `CREATE TABLE IF NOT EXISTS weighbridge_tickets (
  id TEXT PRIMARY KEY NOT NULL,
  ticket_number INTEGER NOT NULL UNIQUE,
  vehicle_number TEXT NOT NULL,
  vehicle_id TEXT,
  party_id TEXT,
  material_id TEXT,
  ticket_type TEXT NOT NULL DEFAULT 'OUTGOING',
  status TEXT NOT NULL DEFAULT 'FIRST_WEIGHT',
  gross_weight REAL,
  gross_time DATETIME,
  tare_weight REAL,
  tare_time DATETIME,
  net_weight REAL,
  linked_sale_id TEXT UNIQUE,
  linked_boulder_id TEXT UNIQUE,
  remarks TEXT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)`,
  `CREATE TABLE IF NOT EXISTS maintenance_records (
  id TEXT PRIMARY KEY NOT NULL,
  vehicle_id TEXT NOT NULL,
  date DATETIME NOT NULL,
  engine_hours REAL NOT NULL,
  service_type TEXT NOT NULL,
  description TEXT,
  cost REAL NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (vehicle_id) REFERENCES vehicles(id) ON DELETE CASCADE
)`,
  `CREATE TABLE IF NOT EXISTS maintenance_schedules (
  id TEXT PRIMARY KEY NOT NULL,
  vehicle_id TEXT NOT NULL,
  service_type TEXT NOT NULL,
  interval_hours REAL,
  interval_days INTEGER,
  next_due_hours REAL,
  next_due_date DATETIME,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (vehicle_id) REFERENCES vehicles(id) ON DELETE CASCADE
)`,
  `CREATE TABLE IF NOT EXISTS vehicle_stats (
  id TEXT PRIMARY KEY NOT NULL,
  vehicle_id TEXT NOT NULL UNIQUE,
  engine_hours REAL NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (vehicle_id) REFERENCES vehicles(id) ON DELETE CASCADE
)`
];

const BASELINE_INDEXES: string[] = [
  "CREATE INDEX IF NOT EXISTS vehicles_party_id_idx ON vehicles (party_id)",
  "CREATE INDEX IF NOT EXISTS vehicles_party_name_idx ON vehicles (party_name)",
  "CREATE INDEX IF NOT EXISTS outgoing_sales_vehicle_id_idx ON outgoing_sales (vehicle_id)",
  "CREATE INDEX IF NOT EXISTS outgoing_sales_party_id_idx ON outgoing_sales (party_id)",
  "CREATE INDEX IF NOT EXISTS outgoing_sales_material_id_idx ON outgoing_sales (material_id)",
  "CREATE INDEX IF NOT EXISTS outgoing_sales_sale_date_idx ON outgoing_sales (sale_date)",
  "CREATE INDEX IF NOT EXISTS outgoing_sales_vehicle_number_idx ON outgoing_sales (vehicle_number)",
  "CREATE INDEX IF NOT EXISTS outgoing_sales_party_name_idx ON outgoing_sales (party_name)",
  "CREATE INDEX IF NOT EXISTS outgoing_sales_material_name_idx ON outgoing_sales (material_name)",
  "CREATE INDEX IF NOT EXISTS financial_events_event_id_idx ON financial_events (event_id)",
  "CREATE INDEX IF NOT EXISTS financial_events_correlation_id_idx ON financial_events (correlation_id)",
  "CREATE INDEX IF NOT EXISTS financial_events_entity_id_idx ON financial_events (entity_id)",
  "CREATE INDEX IF NOT EXISTS financial_events_event_type_idx ON financial_events (event_type)",
  "CREATE INDEX IF NOT EXISTS financial_events_entity_type_idx ON financial_events (entity_type)",
  "CREATE INDEX IF NOT EXISTS financial_events_created_at_idx ON financial_events (created_at)",
  "CREATE INDEX IF NOT EXISTS financial_events_entity_type_entity_id_idx ON financial_events (entity_type, entity_id)",
  "CREATE INDEX IF NOT EXISTS ledger_entries_financial_event_id_idx ON ledger_entries (financial_event_id)",
  "CREATE INDEX IF NOT EXISTS ledger_entries_correlation_id_idx ON ledger_entries (correlation_id)",
  "CREATE INDEX IF NOT EXISTS ledger_entries_entity_id_idx ON ledger_entries (entity_id)",
  "CREATE INDEX IF NOT EXISTS ledger_entries_event_type_idx ON ledger_entries (event_type)",
  "CREATE INDEX IF NOT EXISTS ledger_entries_entity_type_idx ON ledger_entries (entity_type)",
  "CREATE INDEX IF NOT EXISTS ledger_entries_entry_date_idx ON ledger_entries (entry_date)",
  "CREATE INDEX IF NOT EXISTS ledger_entries_created_at_idx ON ledger_entries (created_at)",
  "CREATE INDEX IF NOT EXISTS ledger_entries_entity_type_entity_id_idx ON ledger_entries (entity_type, entity_id)",
  "CREATE INDEX IF NOT EXISTS day_books_business_date_idx ON day_books (business_date)",
  "CREATE INDEX IF NOT EXISTS day_book_expense_entries_day_book_id_idx ON day_book_expense_entries (day_book_id)",
  "CREATE INDEX IF NOT EXISTS day_book_expense_entries_source_event_id_idx ON day_book_expense_entries (source_event_id)",
  "CREATE INDEX IF NOT EXISTS day_book_expense_entries_entry_date_idx ON day_book_expense_entries (entry_date)",
  "CREATE INDEX IF NOT EXISTS incoming_boulder_vehicle_id_idx ON incoming_boulder (vehicle_id)",
  "CREATE INDEX IF NOT EXISTS incoming_boulder_party_id_idx ON incoming_boulder (party_id)",
  "CREATE INDEX IF NOT EXISTS incoming_boulder_material_id_idx ON incoming_boulder (material_id)",
  "CREATE INDEX IF NOT EXISTS incoming_boulder_date_idx ON incoming_boulder (date)",
  "CREATE INDEX IF NOT EXISTS incoming_boulder_vehicle_number_idx ON incoming_boulder (vehicle_number)",
  "CREATE INDEX IF NOT EXISTS incoming_boulder_party_name_idx ON incoming_boulder (party_name)",
  "CREATE INDEX IF NOT EXISTS incoming_boulder_material_name_idx ON incoming_boulder (material_name)",
  "CREATE INDEX IF NOT EXISTS party_credit_party_id_idx ON party_credit (party_id)",
  "CREATE INDEX IF NOT EXISTS party_credit_sale_id_idx ON party_credit (sale_id)",
  "CREATE INDEX IF NOT EXISTS party_credit_party_name_idx ON party_credit (party_name)",
  "CREATE INDEX IF NOT EXISTS party_credit_status_idx ON party_credit (status)",
  "CREATE INDEX IF NOT EXISTS party_collections_party_id_idx ON party_collections (party_id)",
  "CREATE INDEX IF NOT EXISTS party_collections_source_event_id_idx ON party_collections (source_event_id)",
  "CREATE INDEX IF NOT EXISTS party_collections_party_name_idx ON party_collections (party_name)",
  "CREATE INDEX IF NOT EXISTS party_collections_collection_date_idx ON party_collections (collection_date)",
  "CREATE INDEX IF NOT EXISTS party_ledger_party_id_idx ON party_ledger (party_id)",
  "CREATE INDEX IF NOT EXISTS party_ledger_ref_id_idx ON party_ledger (ref_id)",
  "CREATE INDEX IF NOT EXISTS party_ledger_party_name_idx ON party_ledger (party_name)",
  "CREATE INDEX IF NOT EXISTS party_ledger_date_idx ON party_ledger (date)",
  "CREATE INDEX IF NOT EXISTS party_ledger_created_at_idx ON party_ledger (created_at)",
  "CREATE INDEX IF NOT EXISTS cash_transfers_date_idx ON cash_transfers (date)",
  "CREATE INDEX IF NOT EXISTS cash_transfers_user_name_idx ON cash_transfers (user_name)",
  "CREATE INDEX IF NOT EXISTS party_payments_party_id_idx ON party_payments (party_id)",
  "CREATE INDEX IF NOT EXISTS party_payments_source_event_id_idx ON party_payments (source_event_id)",
  "CREATE INDEX IF NOT EXISTS party_payments_party_name_idx ON party_payments (party_name)",
  "CREATE INDEX IF NOT EXISTS party_payments_payment_date_idx ON party_payments (payment_date)",
  "CREATE INDEX IF NOT EXISTS employee_credit_employee_name_idx ON employee_credit (employee_name)",
  "CREATE INDEX IF NOT EXISTS employee_credit_expected_due_date_idx ON employee_credit (expected_due_date)",
  "CREATE INDEX IF NOT EXISTS employee_credit_status_idx ON employee_credit (status)",
  "CREATE INDEX IF NOT EXISTS day_book_entries_entry_date_idx ON day_book_entries (entry_date)",
  "CREATE INDEX IF NOT EXISTS audit_logs_entity_id_idx ON audit_logs (entity_id)",
  "CREATE INDEX IF NOT EXISTS audit_logs_entity_name_idx ON audit_logs (entity_name)",
  "CREATE INDEX IF NOT EXISTS audit_logs_action_idx ON audit_logs (action)",
  "CREATE INDEX IF NOT EXISTS audit_logs_created_at_idx ON audit_logs (created_at)",
  "CREATE INDEX IF NOT EXISTS audit_logs_entity_name_entity_id_idx ON audit_logs (entity_name, entity_id)",
  "CREATE INDEX IF NOT EXISTS other_credits_expected_due_date_idx ON other_credits (expected_due_date)",
  "CREATE INDEX IF NOT EXISTS other_credits_status_idx ON other_credits (status)",
  "CREATE INDEX IF NOT EXISTS expenses_party_id_idx ON expenses (party_id)",
  "CREATE INDEX IF NOT EXISTS expenses_vehicle_id_idx ON expenses (vehicle_id)",
  "CREATE INDEX IF NOT EXISTS expenses_source_event_id_idx ON expenses (source_event_id)",
  "CREATE INDEX IF NOT EXISTS expenses_expense_date_idx ON expenses (expense_date)",
  "CREATE INDEX IF NOT EXISTS expenses_party_name_idx ON expenses (party_name)",
  "CREATE INDEX IF NOT EXISTS expenses_vehicle_number_idx ON expenses (vehicle_number)",
  "CREATE INDEX IF NOT EXISTS employee_ledgers_employee_id_idx ON employee_ledgers (employee_id)",
  "CREATE INDEX IF NOT EXISTS employee_ledgers_date_idx ON employee_ledgers (date)",
  "CREATE INDEX IF NOT EXISTS employee_ledgers_created_at_idx ON employee_ledgers (created_at)",
  "CREATE INDEX IF NOT EXISTS fuel_purchases_vehicle_id_idx ON fuel_purchases (vehicle_id)",
  "CREATE INDEX IF NOT EXISTS fuel_purchases_source_event_id_idx ON fuel_purchases (source_event_id)",
  "CREATE INDEX IF NOT EXISTS fuel_purchases_date_idx ON fuel_purchases (date)",
  "CREATE INDEX IF NOT EXISTS fuel_purchases_vehicle_number_idx ON fuel_purchases (vehicle_number)",
  "CREATE INDEX IF NOT EXISTS sync_state_last_synced_at_idx ON sync_state (last_synced_at)",
  "CREATE INDEX IF NOT EXISTS sync_state_status_idx ON sync_state (status)",
  "CREATE INDEX IF NOT EXISTS global_settings_quarry_name_idx ON global_settings (quarry_name)",
  "CREATE INDEX IF NOT EXISTS inventory_stock_last_updated_idx ON inventory_stock (last_updated)",
  "CREATE INDEX IF NOT EXISTS inventory_transactions_stock_id_idx ON inventory_transactions (stock_id)",
  "CREATE INDEX IF NOT EXISTS inventory_transactions_reference_id_idx ON inventory_transactions (reference_id)",
  "CREATE INDEX IF NOT EXISTS inventory_transactions_date_idx ON inventory_transactions (date)",
  "CREATE INDEX IF NOT EXISTS inventory_transactions_created_at_idx ON inventory_transactions (created_at)",
  "CREATE INDEX IF NOT EXISTS weighbridge_tickets_vehicle_id_idx ON weighbridge_tickets (vehicle_id)",
  "CREATE INDEX IF NOT EXISTS weighbridge_tickets_party_id_idx ON weighbridge_tickets (party_id)",
  "CREATE INDEX IF NOT EXISTS weighbridge_tickets_material_id_idx ON weighbridge_tickets (material_id)",
  "CREATE INDEX IF NOT EXISTS weighbridge_tickets_linked_sale_id_idx ON weighbridge_tickets (linked_sale_id)",
  "CREATE INDEX IF NOT EXISTS weighbridge_tickets_linked_boulder_id_idx ON weighbridge_tickets (linked_boulder_id)",
  "CREATE INDEX IF NOT EXISTS weighbridge_tickets_vehicle_number_idx ON weighbridge_tickets (vehicle_number)",
  "CREATE INDEX IF NOT EXISTS weighbridge_tickets_status_idx ON weighbridge_tickets (status)",
  "CREATE INDEX IF NOT EXISTS weighbridge_tickets_gross_time_idx ON weighbridge_tickets (gross_time)",
  "CREATE INDEX IF NOT EXISTS weighbridge_tickets_tare_time_idx ON weighbridge_tickets (tare_time)",
  "CREATE INDEX IF NOT EXISTS maintenance_records_vehicle_id_idx ON maintenance_records (vehicle_id)",
  "CREATE INDEX IF NOT EXISTS maintenance_records_date_idx ON maintenance_records (date)",
  "CREATE INDEX IF NOT EXISTS maintenance_schedules_vehicle_id_idx ON maintenance_schedules (vehicle_id)",
  "CREATE INDEX IF NOT EXISTS maintenance_schedules_next_due_date_idx ON maintenance_schedules (next_due_date)",
  "CREATE INDEX IF NOT EXISTS vehicle_stats_vehicle_id_idx ON vehicle_stats (vehicle_id)"
];

const migration: Migration = {
  version: 1,
  id: "001_baseline",
  description: "Create all 32 model tables and indexes (immutable frozen snapshot)",

  up: async (_prisma: PrismaClient): Promise<string[]> => {
    return [...BASELINE_TABLES, ...BASELINE_INDEXES];
  },
};

export default migration;
