;;Tally.ERP 9 workstation specific parameters file
[TALLY]

;;** Gateway server configuration, 
;; ** Tally Gateway Server=server:port
Tally Gateway Server=USER-PC:10000

;;Specify list of TDL files for user defined reports and changes, 
;; ** TO STOP LOADING TDL FILES, set the following line to NO
User TDL=No

;;Specify the path of Capsule Folder
Capsule=

;;Specify the path of Local Help Folder
Help=C:\Program Files\Tally\Tally.ERP9\help

LicTimeout=

;;Specify list of companies to preload, 
;; ** TO STOP DEFAULT LOADING set the following line to NO
Default Companies=No
Load=10000

;;Specify the list of gold gateway servers to subscribe
Tally Gold License Server=

;;Specify location of Data files
Data=d:\Tally.ERP9\Data

Client Server=None
ServerPort=9000
Enable ODBC Server=Yes
Load Buffering=Yes
Ignore Tcp Timeout=Yes

AutoInstallNumber=

;;Specify location of TALLYSAV.tsf (saved configuration of Tally)
Config=C:\Program Files\Tally\Tally.ERP9

;;Specify location of Language Files
LangPath=C:\Program Files\Tally\Tally.ERP9\Lang

;;Specify location where files are created during export by default
Export Path=C:\Program Files\Tally\Tally.ERP9

;;Specify Color details of local monitor
Color=Yes
Sound=Yes

Width=1415
Height=845
